'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {initializeApp} from 'firebase/app';
import {createUserWithEmailAndPassword,getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut,User} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,getFirestore,onSnapshot,query,serverTimestamp,setDoc,updateDoc,where} from 'firebase/firestore';

const app=initializeApp({apiKey:'AIzaSyCzO4Rit3gB9Uw_RRZoVSbPM2XHfAyoENk',authDomain:'controle-de-ar.firebaseapp.com',projectId:'controle-de-ar',storageBucket:'controle-de-ar.firebasestorage.app',messagingSenderId:'298625930135',appId:'1:298625930135:web:dcdbfc2be30ec2f9faead2'});
const auth=getAuth(app),db=getFirestore(app);
type Role='fiscal'|'admin'; type View='home'|'new'|'list';
type AR={id:string;codigo:string;destinatario:string;endereco:string;cep:string;cidade:string;uf:string;pais:string;conteudo:string;observacao:string;status:'aguardando'|'recebido';criadoPor:string;criadoPorNome:string;criadoEm?:any;recebidoEm?:any;recebidoPorNome?:string};
const empty={destinatario:'',endereco:'',cep:'',cidade:'',uf:'SP',pais:'BRASIL',conteudo:'',observacao:''};
const date=(v:any)=>v?.toDate?v.toDate().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'agora';
const err=(e:any)=>e?.code?.includes('invalid-credential')?'E-mail ou senha não conferem.':e?.code?.includes('email-already')?'Este e-mail já está cadastrado.':e?.code?.includes('weak-password')?'A senha deve ter ao menos 6 caracteres.':'Não foi possível concluir. Verifique a conexão.';

export default function Home(){
 const [user,setUser]=useState<User|null>(null),[role,setRole]=useState<Role>('fiscal'),[name,setName]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState<View>('home'),[ars,setArs]=useState<AR[]>([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('todos'),[form,setForm]=useState(empty),[selected,setSelected]=useState<AR|null>(null),[toast,setToast]=useState('');
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(u){const p=(await getDoc(doc(db,'usuarios',u.uid))).data();setRole(p?.role||'fiscal');setName(p?.nome||u.email?.split('@')[0]||'Usuário')}setLoading(false)}),[]);
 useEffect(()=>{if(!user)return;const source=role==='admin'?query(collection(db,'ars')):query(collection(db,'ars'),where('criadoPor','==',user.uid));return onSnapshot(source,s=>setArs(s.docs.map(d=>({id:d.id,...d.data()} as AR)).sort((a,b)=>(b.criadoEm?.seconds||0)-(a.criadoEm?.seconds||0))),e=>flash(e.code==='permission-denied'?'Acesso ao banco bloqueado. Publique as regras do Firestore incluídas no projeto.':'Não foi possível atualizar os ARs.'))},[user,role]);
 const mine=ars.filter(a=>a.criadoPor===user?.uid),pending=ars.filter(a=>a.status==='aguardando');
 const visible=useMemo(()=>ars.filter(a=>(role==='admin'||a.criadoPor===user?.uid)&&(filter==='todos'||a.status===filter)&&[a.codigo,a.destinatario,a.cidade,a.criadoPorNome].join(' ').toLowerCase().includes(search.toLowerCase())),[ars,role,user,filter,search]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),3000)};
 async function save(e:FormEvent){e.preventDefault();const codigo=`AR-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;try{await addDoc(collection(db,'ars'),{...form,codigo,status:'aguardando',criadoPor:user!.uid,criadoPorNome:name,criadoEm:serverTimestamp()});setForm(empty);setView('list');flash(`${codigo} enviado para a caixa de entrada.`)}catch(e){flash(err(e))}}
 async function receive(a:AR){await updateDoc(doc(db,'ars',a.id),{status:'recebido',recebidoEm:serverTimestamp(),recebidoPor:user!.uid,recebidoPorNome:name});setSelected(null);flash('Recebimento confirmado com sucesso.')}
 if(loading)return <main className="loading"><i/>Carregando…</main>;if(!user)return <Login/>;
 const nav=(v:View,label:string,icon:string)=><button className={view===v?'active':''} onClick={()=>setView(v)}>{icon}<span>{label}</span>{v==='list'&&role==='admin'&&pending.length>0&&<em>{pending.length}</em>}</button>;
 return <div className="shell">{toast&&<div className="toast">✓ {toast}</div>}<header><button className="brand" onClick={()=>setView('home')}><b>AR</b><span>Controle de AR<small>Subprefeitura Penha</small></span></button><div className="profile"><i>{name[0]?.toUpperCase()}</i><span><b>{name}</b><small>{role==='admin'?'Administrativo':'Fiscal'}</small></span><button onClick={()=>signOut(auth)}>Sair</button></div></header><nav>{nav('home','Início','⌂')}{nav('new','Novo AR','＋')}{nav('list',role==='admin'?'Caixa de entrada':'Meus ARs','▤')}</nav><main className="content">
 {view==='home'&&<><section className="hero"><div><p>Olá, {name.split(' ')[0]}!</p><h1>{role==='admin'&&pending.length?`Você tem ${pending.length} AR${pending.length>1?'s':''} para receber`:'Tudo certo por aqui'}</h1><span>{role==='admin'?'Os ARs dos fiscais chegam automaticamente na sua caixa de entrada.':'Cadastre um aviso ou acompanhe os que você já enviou.'}</span></div><button className="primary" onClick={()=>setView(role==='admin'&&pending.length?'list':'new')}>{role==='admin'&&pending.length?'Ver caixa de entrada':'Cadastrar novo AR'} →</button></section><section className="stats"><article className="yellow"><i>⌛</i><span><small>Aguardando recebimento</small><b>{role==='admin'?pending.length:mine.filter(a=>a.status==='aguardando').length}</b></span></article><article className="green"><i>✓</i><span><small>Recebidos</small><b>{(role==='admin'?ars:mine).filter(a=>a.status==='recebido').length}</b></span></article><article className="blue"><i>▤</i><span><small>Cadastrados por você</small><b>{mine.length}</b></span></article></section><Panel title={role==='admin'?'Aguardando sua confirmação':'Seus últimos ARs'} items={(role==='admin'?pending:mine).slice(0,5)} role={role} open={setSelected}/></>}
 {view==='new'&&<ARGenerator form={form} setForm={setForm} save={save}/>} 
 {view==='list'&&<section><div className="page-title list-title"><span><p>{role==='admin'?'Recebimentos':'Acompanhamento'}</p><h1>{role==='admin'?'Caixa de entrada':'Meus ARs'}</h1><small>{visible.length} registro{visible.length!==1?'s':''}</small></span><button className="primary" onClick={()=>setView('new')}>＋ Novo AR</button></div><div className="filters"><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar código, destinatário ou cidade…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos os status</option><option value="aguardando">Aguardando</option><option value="recebido">Recebidos</option></select></div><Panel items={visible} role={role} open={setSelected}/></section>}
 </main>{selected&&<Modal ar={selected} admin={role==='admin'} close={()=>setSelected(null)} receive={()=>receive(selected)}/>}</div>
}

function ARGenerator({form,setForm,save}:{form:typeof empty,setForm:(v:typeof empty)=>void,save:(e:FormEvent)=>void}){
 const val=(v:string,fallback='---')=>v.trim().toUpperCase()||fallback;
 return <section className="generator-page">
  <div className="page-title"><button onClick={()=>history.back()}>←</button><span><p>Novo aviso</p><h1>Gerador de AR</h1><small>Preencha, confira a visualização e envie o aviso.</small></span></div>
  <div className="generator-layout">
   <form className="generator-form" onSubmit={save}>
    <div className="generator-heading"><b>AR</b><h2>Gerador de AR</h2></div>
    <p>Preencha os dados do destinatário. O verso (remetente) já possui os dados da subprefeitura pré-preenchidos para impressão.</p>
    <Field label="Nome do Destinatário" value={form.destinatario} set={v=>setForm({...form,destinatario:v})} required/>
    <Field label="Endereço" value={form.endereco} set={v=>setForm({...form,endereco:v})} required/>
    <div className="generator-fields"><Field label="CEP" value={form.cep} set={v=>{let d=v.replace(/\D/g,'').slice(0,8);setForm({...form,cep:d.length>5?d.slice(0,5)+'-'+d.slice(5):d})}} required/><Field label="Cidade" value={form.cidade} set={v=>setForm({...form,cidade:v})} required/></div>
    <div className="generator-fields"><Field label="UF" value={form.uf} set={v=>setForm({...form,uf:v.toUpperCase().slice(0,2)})} required/><Field label="País" value={form.pais} set={v=>setForm({...form,pais:v})}/></div>
    <Field label="Declaração de Conteúdo" value={form.conteudo} set={v=>setForm({...form,conteudo:v})}/>
    <label>Observação interna<input value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Opcional — não aparece na impressão"/></label>
    <div className="generator-actions"><button className="ar-submit" type="submit">Cadastrar e enviar AR</button><button type="button" className="ar-print" onClick={()=>window.print()}>Gerar PDF / Imprimir</button><button type="button" className="ar-clear" onClick={()=>setForm(empty)}>Limpar</button></div>
   </form>
   <div className="ar-previews">
    <div><h3>FRENTE (DESTINATÁRIO)</h3><article className="ar-paper ar-front">
     <header><span className="correios">▰<small>Correios</small></span><h2>AVISO DE RECEBIMENTO</h2><b>PREENCHER COM<br/>LETRA DE FORMA</b></header>
     <h4>DESTINATÁRIO DO OBJETO</h4>
     <div className="ar-grid"><Cell span="full" label="NOME OU RAZÃO SOCIAL DO DESTINATÁRIO" value={val(form.destinatario)}/><Cell span="full" label="ENDEREÇO" value={val(form.endereco)}/><Cell span="cep" label="CEP" value={val(form.cep)}/><Cell span="city" label="CIDADE" value={val(form.cidade)}/><Cell label="UF" value={val(form.uf,'--')}/><Cell label="PAÍS" value={val(form.pais,'BRASIL')}/><Cell span="usage" label="USO DOS DADOS" value="DOU CIÊNCIA DOS DADOS COLETADOS NO ATO DA ENTREGA DO OBJETO, QUE PODERÃO SER UTILIZADOS PARA FINS DE COMPROVAÇÃO DA PRESTAÇÃO DO SERVIÇO."/><Cell span="content" label="DECLARAÇÃO DE CONTEÚDO (OPCIONAL)" value={val(form.conteudo)}/><Cell span="signature" label="ASSINATURA DO RECEBEDOR"/><Cell span="date" label="DATA DE REC." value="____ / ____ / ____"/><Cell span="stamp" label="CARIMBO"/><Cell span="receiver" label="NOME LEGÍVEL DO RECEBEDOR"/><Cell span="doc" label="DOC. IDENTIFICAÇÃO"/><Cell span="rubric" label="RUBRICA/MAT. EMPREGADO"/></div>
     <footer>ENDEREÇO PARA DEVOLUÇÃO NO VERSO</footer>
    </article></div>
    <div><h3>VERSO (REMETENTE / POSTAGEM)</h3><article className="ar-paper ar-back">
     <header><span className="correios">▰<small>Correios</small></span><span className="ar-box">AVISO DE<br/>RECEBIMENTO</span><strong>AR</strong><i>( CÓDIGO DE BARRAS OU Nº DE REGISTRO DO OBJETO )</i></header>
     <div className="post-grid"><Cell label="DATA DE POSTAGEM" value="______ / ______ / ________"/><Cell span="attempts" label="TENTATIVAS DE ENTREGA" value="____ / ____ / ____　　____ / ____ / ____　　____ / ____ / ____"/><Cell label="UNIDADE DE POSTAGEM"/><Cell span="attempts" value="____ : ____ h　　　____ : ____ h　　　____ : ____ h"/></div>
     <div className="return-block"><b>ENDEREÇO PARA DEVOLUÇÃO</b><div><Cell span="full" label="NOME OU RAZÃO SOCIAL DO REMETENTE" value="SUBPREFEITURA PENHA - SUPERVISÃO DE FISCALIZAÇÃO - CPDU"/><Cell span="full" label="ENDEREÇO PARA DEVOLUÇÃO" value="RUA CANDAPUÍ, 492 - VILA MARIETA"/><div className="return-row"><Cell span="return-city" label="CIDADE" value="SÃO PAULO"/><Cell label="UF" value="SP"/><Cell label="" value="BRASIL"/></div><div className="cep-boxes"><i>0</i><i>3</i><i>6</i><i>2</i><i>1</i><b>-</b><i>0</i><i>0</i><i>0</i></div></div></div>
    </article></div>
   </div>
  </div>
 </section>
}
function Cell({label='',value='',span=''}:{label?:string,value?:string,span?:string}){return <div className={`ar-cell ${span}`}><small>{label}</small>{value&&<b>{value}</b>}</div>}

function Login(){const[first,setFirst]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function go(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(first){const c=await createUserWithEmailAndPassword(auth,email,pass);await setDoc(doc(db,'usuarios',c.user.uid),{nome:name,email,role:'fiscal',criadoEm:serverTimestamp()})}else await signInWithEmailAndPassword(auth,email,pass)}catch(e){setError(err(e))}finally{setBusy(false)}}return <main className="login"><section className="login-left"><b>AR</b><h1>Avisos de Recebimento,<br/><em>sem complicação.</em></h1><p>Cadastre, acompanhe e receba ARs em um só lugar.</p><div>✓ Simples de usar　 ✓ Atualização em tempo real　 ✓ Dados centralizados</div></section><section className="login-box"><div className="mobile-brand"><b>AR</b> Controle de AR</div><p>{first?'Primeiro acesso':'Bem-vindo de volta'}</p><h2>{first?'Crie seu acesso de fiscal':'Entre na sua conta'}</h2><small>{first?'Contas administrativas são liberadas pelo responsável.':'Use seu e-mail e senha para continuar.'}</small><form onSubmit={go}>{first&&<Field label="Seu nome" value={name} set={setName} required/>}<Field label="E-mail" value={email} set={setEmail} required type="email"/><Field label="Senha" value={pass} set={setPass} required type="password"/>{error&&<div className="error">! {error}</div>}<button className="primary" disabled={busy}>{busy?'Aguarde…':first?'Criar acesso':'Entrar'} →</button></form><button className="switch" onClick={()=>{setFirst(!first);setError('')}}>{first?'Já tenho cadastro. Entrar':'Primeiro acesso de fiscal'}</button><footer>Prefeitura de São Paulo · Subprefeitura Penha</footer></section></main>}
function Field({label,value,set,wide,required,type='text'}:{label:string,value:string,set:(v:string)=>void,wide?:boolean,required?:boolean,type?:string}){return <label className={wide?'wide':''}>{label}<input type={type} required={required} value={value} onChange={e=>set(e.target.value)} placeholder={label.replace(' *','')}/></label>}
function Panel({title,items,role,open}:{title?:string,items:AR[],role:Role,open:(a:AR)=>void}){return <section className="panel">{title&&<div className="panel-head"><h2>{title}</h2><small>Selecione um AR para ver os detalhes.</small></div>}{!items.length?<div className="empty"><i>✓</i><h3>Nenhum AR por aqui</h3><p>Os avisos aparecerão automaticamente nesta lista.</p></div>:items.map(a=><button className="row" key={a.id} onClick={()=>open(a)}><i className={a.status}/><span className="who"><b>{a.destinatario}</b><small>{a.codigo} · {a.cidade}/{a.uf}</small></span>{role==='admin'&&<span className="creator"><small>Cadastrado por</small><b>{a.criadoPorNome}</b></span>}<span className="when"><small>{a.status==='recebido'?'Recebido em':'Cadastrado em'}</small><b>{date(a.status==='recebido'?a.recebidoEm:a.criadoEm)}</b></span><em className={a.status}>{a.status==='recebido'?'✓ Recebido':'⌛ Aguardando'}</em><strong>›</strong></button>)}</section>}
function Modal({ar,admin,close,receive}:{ar:AR,admin:boolean,close:()=>void,receive:()=>void}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><button className="x" onClick={close}>×</button><em className={ar.status}>{ar.status==='recebido'?'✓ Recebido':'⌛ Aguardando recebimento'}</em><h2>{ar.codigo}</h2><p>Cadastrado por {ar.criadoPorNome} em {date(ar.criadoEm)}</p><div className="details"><span><small>Destinatário</small><b>{ar.destinatario}</b></span><span><small>Endereço</small><b>{ar.endereco}</b><p>{ar.cep} · {ar.cidade}/{ar.uf} · {ar.pais}</p></span>{ar.conteudo&&<span><small>Conteúdo</small><b>{ar.conteudo}</b></span>}{ar.observacao&&<span><small>Observação interna</small><b>{ar.observacao}</b></span>}</div><footer><button onClick={()=>window.print()}>Imprimir ficha</button>{admin&&ar.status==='aguardando'&&<button className="primary" onClick={receive}>✓ Confirmar recebimento</button>}</footer><div className="print"><h1>AVISO DE RECEBIMENTO</h1><p><b>DESTINATÁRIO:</b> {ar.destinatario}</p><p><b>ENDEREÇO:</b> {ar.endereco}</p><p><b>CEP / CIDADE / UF:</b> {ar.cep} — {ar.cidade}/{ar.uf}</p><p><b>CONTEÚDO:</b> {ar.conteudo||'—'}</p><div>ASSINATURA DO RECEBEDOR</div><small>REMETENTE: SUBPREFEITURA PENHA — SUPERVISÃO DE FISCALIZAÇÃO — CPDU<br/>RUA CANDAPUÍ, 492 — VILA MARIETA — SÃO PAULO/SP — CEP 03621-000</small></div></section></div>}
